### ISSUE TITLE
设计模式和算法的电子书无法查看

### ISSUE THREAD

**Issue by zhaoruobing** [miyuesc/documents#1]
非常感谢您的整理！
请问为什么设计模式和算法的电子书无法查看呢？
https://miyuefe.lanzous.com/b01zys6di 这个链接访问也失败

**Comment by miyuesc** [comment]
https://miyuefe.lanzoui.com/b01zys6ch
密码:44xj

> 蓝奏云部分地区的网络问题造成的，这是更新后的地址
